flags: {}
packages:
- '.'
#- location: /home/roman/OpenCog/atomspace/opencog/haskell
#- location: /home/roman/Lojban/test/tersmu

- location:
    git: https://github.com/rTreutlein/tersmu-0.2
    commit: 91a68f4c815d3ee45fcd07bc839f1d2d0c8bfda1

extra-deps: [opencog-atomspace-0.1.0.3]
resolver: lts-3.6
extra-lib-dirs: [/usr/local/lib/opencog]
ghc-options:
    opencog-lojbantoatoms: -lHSrts-ghc7.10.2
